### ISSUE TITLE
Doc: clarify 'disconnectAfterSeconds'

### ISSUE THREAD

**Issue by teuf22** [upscopeio/js-api#1]
In the documentation, disconnectAfterSeconds is described as
"Number of seconds of inactivity after which Upscope disconnects from the server"

Is the the number of seconds of inactivity since the Upscope.init(), or the number of seconds of inactivity since the screen share started ?

Thank you

**Comment by joedelia** [comment]
Clarified this in the docs!

> Number of seconds of inactivity after which Upscope disconnects from the server. This only applies if a session is not active, and the connection is re-established when the tab regains focus, the cursor is moved, or the keyboard is used.
